### ISSUE TITLE
Bearer auth not work

### ISSUE THREAD

**Issue by chrno1209** [SkeLLLa/fastify-oas#11]
Hi,
First of all, thanks for great plugin, I am new to Fastify and on my way to create the first API system on it.
However, after many tries I cannot setup swagger to use Bearer auth, can you please give some example on how to archive that?

Many thanks.

**Comment by SkeLLLa** [comment]
Hi. Could you tell what exactly doesn't work? Maybe you could share some examples of what have you tried already.

**Comment by chrno1209** [comment]
Hi @SkeLLLa 
I've just tried your suggestion and it works like a charm.
Is there any way to add security pointing to my bearer auth in global configuration instead of each route?

Thanks.

**Comment by SkeLLLa** [comment]
I think it will apply to all routes if you'll add `security: [{myAuth: []}],` to root of `swagger` object.

**Comment by chrno1209** [comment]
Hi @SkeLLLa 
Thanks, just tried and it works, I haven't noticed that security is an array instead of an object that contain the name of auth declare above.
You save my day :)
