### ISSUE TITLE
Document for build custom swagger ui

### ISSUE THREAD

**Issue by mhf-ir** [SkeLLLa/fastify-oas#15]
How to use this awesome plugin with custom swagger ui ?

Is there any change to we have it ?

**Comment by SkeLLLa** [comment]
Basically this plugin generates swagger document in yaml and json format. And as addition it has swagger-ui html page that just build UI based on those swagger configuration.

So what you need - is just host your custom version of swagger-ui somewhere and configure it to get swagger config file from something like `http://example.com/api/documentation/json` or http://<your_domain>/<oas_plugin_route_prefix>/yaml
