### ISSUE TITLE
Option to generate references instead of replacing reference

### ISSUE THREAD

**Issue by ealtuna** [SkeLLLa/fastify-oas#16]
I am trying to use oneOf for code generation and the output is not what I am expecting. I traced the root cause of the issue and I think is related with fact that fastify-oas is replacing my references.

For example:

```
fastify.addSchema({
        $id: "Cat",
        type: "object",
        properties: { name: { type: "string" } }
});
fastify.addSchema({
        $id: "Dog",
        type: "object",
        properties: { legs: { type: "integer" } }
});
```

Used in a route: 

```
animal: {
  oneOf: [
     "Cat#",
     "Dog#"
  ]
}
```

As result I am getting for the path:

```
animal: {
  oneOf: [
      {
        type: "object",
        properties: { name: { type: "string" } }
     },
     {
        type: "object",
        properties: { legs: { type: "integer" } }
    }
  ]
}
```

It would be nice to have the option to get the references instead (like using $ref)

**Comment by SkeLLLa** [comment]
@ealtuna if I'm not mistaken that's how Fastify works. It resolves the references on schemaCompile and replace them with actual schema object.
Maybe there's some way to restore the id of schema, but I didn't investigate this.

Do you want to try to make a PR for this?

**Comment by ealtuna** [comment]
@SkeLLLa never mind, my mind. There are two ways to reference in Fastify, the replace-way and the ref-way, as stated in [Validation and Serialization](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md). Thank you for your fast response and pointing to the right direction. This issue can be closed.
