### ISSUE TITLE
Dynamic host and urls base on request

### ISSUE THREAD

**Issue by mhf-ir** [SkeLLLa/fastify-oas#18]
Api schema may change such as server information on openapi 3 base on multiple domains.
Not static one during register plugin.
How could we handle it ?
```json
"servers": // ??,
```

**Comment by mhf-ir** [comment]
now we could create hook for change base on request but how could handle this?
```js
    app.addHook('onSend', async (req, reply, payload) => {
      if (req.raw.url === `${this.config.API_PREFIX}/docs/json`) {
        const newPayload = JSON.parse(payload);
        const host = req.headers['x-forwarded-host'] ? req.headers['x-forwarded-host'] : '127.0.0.1';
        const protocol = req.headers['x-forwarded-proto'] ? req.headers['x-forwarded-proto'] : 'http';
        const port = req.headers['x-forwarded-port'] ? req.headers['x-forwarded-port'] : '9000';
        const url = new URL(newPayload.servers[0].url);
        url.host = host;
        url.protocol = protocol;
        url.port = port;
        newPayload.servers[0].url = url.href;
        return JSON.stringify(newPayload);
      }

      return undefined;
    });
```

But how can i use dynamic variable base on request not using fastify hooks?

**Comment by SkeLLLa** [comment]
If your API is relative to path of the main site, then you may set the server url to `/`.
Or you may also use something like `node-config` that will provide static configs based on environment where application is launched.

**Comment by mhf-ir** [comment]
Application lunch already, base on request variables changed not base on starting up.
Consider simple api but about 10k domains.
Such as blogging system.
```
http://user1.blog.tld/api/docs
http://user2.blog.tld/api/docs
...
http://user10000000.blog.tld/api/docs
```

**Comment by SkeLLLa** [comment]
If I understood correctly, putting `/` as server url in config should solve that.

**Comment by fyang1024** [comment]
@SkeLLLa Can you please clarify what config you mean? I don't see a server or serverUrl option in the config list.
I am running the app on http://locahost:5000, and when I click `Execute` on the swagger-ui, it tries to hit `http://127.0.0.1/` for endpoints without the port 5000.
