### ISSUE TITLE
addModels param doesn't do what expected.

### ISSUE THREAD

**Issue by artuuro** [SkeLLLa/fastify-oas#19]
I've tried using `addModels: true` param to enable models view on the UI, although It seems to be not really documented and neither having any effects when setting this to true.

**Comment by SkeLLLa** [comment]
Can you add some details about how do you add your models?

**Comment by artuuro** [comment]
> Can you add some details about how do you add your models?

https://github.com/artuuro/re-backend/blob/master/src/core/Memory.js you can see the loading here, models are located at src/models folder

**Comment by SkeLLLa** [comment]
There are no fastify schemes there, so that's why it doesn't add anything. See https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#adding-a-shared-schema for details.
