### ISSUE TITLE
Required body attributes don't show as required in the model view of the body doc

### ISSUE THREAD

**Issue by AntoineMaitre** [SkeLLLa/fastify-oas#2]
Hi there !

I just noticed that when tagging an attribute of the body as _required_, in the swagger html view, the `little red star` that indicates that the field is required in the body doesn't show on the given field.

![image](https://user-images.githubusercontent.com/14912110/48850788-ab0fde80-eda9-11e8-9576-b4aa4b0a1ec3.png)

Commenting [this line](https://github.com/SkeLLLa/fastify-oas/blob/master/lib/helpers.js#L56) in the code solves the problem and the required fields display as expected in the swagger view.

Do you have any insight on this behavior ? I mean, why deleting the `body.required` ?

Thanks in advance for your answer ;)

And thank you for your efforts on this plugin and keep up the good work ! 👍

**Comment by SkeLLLa** [comment]
Thanks. I'll take a look.

**Comment by AntoineMaitre** [comment]
Hi @SkeLLLa,

Thanks for taking the time of looking at this ! 💯 

I'll try it out as soon as I can and I'll let you know if it solves the problem 👍

**Comment by SkeLLLa** [comment]
Seems this bug was fixed. Feel free to reopen if it occurs again.
