### ISSUE TITLE
Error: fastify-plugin - expected '<2.12.0' fastify version, '2.12.0' is installed

### ISSUE THREAD

**Issue by gblok** [SkeLLLa/fastify-oas#22]
```
module.exports = fp(
  async (fastify, opts) => {
    return openapi(fastify, opts);
  },
  {
    fastify: '<2.12.0',
    name: 'fastify-oas',
  },
);
```
... correct plz

**Comment by SkeLLLa** [comment]
@gblok That's expected. See https://github.com/SkeLLLa/fastify-oas#fastify-support notice.

TLDR: fastify 2.12 has regression that breaks this extension.

**Comment by SkeLLLa** [comment]
@gblok Issue is fixed in Fastify.

https://github.com/fastify/fastify/pull/2108

**Comment by gblok** [comment]
thx )
