### ISSUE TITLE
Option to disable UIs but not the yaml/json spec

### ISSUE THREAD

**Issue by osher** [SkeLLLa/fastify-oas#23]
Hi, 

If it's possible - I'll be grateful, if it is - I can't find how to do it:
I would like the server to serve the OAS json/yaml, but not the SwaggerUI/ReDoc UIs.

Is it supported?

Thanks

**Comment by SkeLLLa** [comment]
@osher no, it's not supported yet. But I think it will be not so hard to add.
If you pass an object like 
```js
{
  ui: true,
  json: true,
  yaml: true
}
```
in `exposeRoute ` https://github.com/SkeLLLa/fastify-oas/blob/master/lib/openapi/index.js#L20
and check those params in https://github.com/SkeLLLa/fastify-oas/blob/master/lib/routes.js#L4 it would do the trick.

Would you like to send PR?

**Comment by SkeLLLa** [comment]
Added in 2.7.0.
