### ISSUE TITLE
Use $ref in body or in response

### ISSUE THREAD

**Issue by FreshYop** [SkeLLLa/fastify-oas#25]
Hi,

Can you provide a sample to use $ref for body or response schema ? 
I'm trying lot of thing but nothing works...

Definition.ts
```
public static Cat = {
        $id: 'Cat',
        type: 'object',
        required: ['id', 'name'],
        properties: {
            _id: { type: 'string', format: 'uuid' },
            name: { type: 'string'},
        }
    };
```

CatRoute.ts : 
```
{
    method: 'POST',
    url: '/api/cat',
    handler: addCatController,
    schema: addCatSwagger
  }
```

ControllerCat.ts
```
  function addCatController = async (req, reply) => {
    try {
      const cat = new CatModel(req.body);
      return cat.save();
    } catch (err) {
      console.error(err);
    }
  }
```

SwaggerCat.ts
```
const add = {
    description: `Create a new Cat`,
    tags: ['cat'],
    summary: `Creates new cat with given values`,
    body: {
        in: 'body',
        name: 'body',
        description: 'Pet object that needs to be added to the store',
        required: true,
        schema: {
          $ref: 'Cat'
        }
      }
    ,
    responses: {
      200: {
        description: 'Successful response',
      }
    }
  };
```

Any any to accept Cat definition in the body of my put request ? 
Same thing for returning one Cat  ? (array of Cat is ok, but how we do with only one object in return )

**Comment by SkeLLLa** [comment]
Ref support was added in https://github.com/SkeLLLa/fastify-oas/pull/17. I personally don't use this approach, so I can't tell you. 
Maybe tests in that PR will give you some idea.

**Comment by patarapolw** [comment]
What? I already can -- https://github.com/patarapolw/ts-openapi-fastify

But I somehow have this problem, [Failed building the schema for ONLY RESPONSE. due error Cannot find reference 'definitions'](https://github.com/fastify/fastify/issues/2281).
