### ISSUE TITLE
Remove custom properties

### ISSUE THREAD

**Issue by firasdib** [SkeLLLa/fastify-oas#28]
In AJV you can add custom properties and validation rules. However, when you generate the json/yaml through fastify-oas, these will be included. Is there a way to filter these?

**Comment by SkeLLLa** [comment]
Can you add some minimal example?

**Comment by firasdib** [comment]
Well, in AJV you can define any custom keywords, you could have something like this:

```json
{ 
  type: 'object',
  additionalProperties: false,
  properties: {
    foo: { type: 'string', format: 'date-time', myCustomKeyword: true }
  }
}
```

**Comment by SkeLLLa** [comment]
@firasdib got it.
It's actually strange, cause all properties are filtered via https://github.com/SkeLLLa/fastify-oas/blob/master/lib/helpers.js#L35 which uses https://github.com/SkeLLLa/fastify-oas/blob/master/lib/helpers.js#L1 whitelist. So if your custom keyword is not from that list it shouldn't appear in result swagger json/yaml.

**Comment by firasdib** [comment]
Interesting. It should be removed, but looks like it wasn't for me. Was this added in a recent version? We are using 2.5.1.

**Comment by SkeLLLa** [comment]
@firasdib, most of properties were there since first release. 
Could you put some breakpoints in places that I've mentioned and try to figure out what's happening in your application?

**Comment by firasdib** [comment]
I will try to find some time to debug this week

**Comment by SkeLLLa** [comment]
Great, if you find anything feel free to submit a PR.
