### ISSUE TITLE
`format` is not supported for numeric data types

### ISSUE THREAD

**Issue by fyang1024** [SkeLLLa/fastify-oas#46]
The following throws error even though it is in the spec https://swagger.io/specification/#:~:text=%222.0%22%20.)-,Format,%7B
```javascript
{
   type: 'number'
   format: 'double'
}
```

**Comment by SkeLLLa** [comment]
Could you please add more details about error you receive and the code example which reproduces the error?

**Comment by fyang1024** [comment]
The error message does like this:
```
due to error unknown format \"double\" is used in schema at path \"#/properties/payload/properties/selectedBenefits/items/properties/lives/items/properties/permanentPercentageRating\""
```
The schema is a bit big, the section below is deeply embedded as you can probably tell from the error message
```
permanentPercentageRating: {
    type: 'number',
    format: 'double',
    example: 50
}
```

**Comment by SkeLLLa** [comment]
Format is not valid JSON schema keyword for number type, unless you'll add it manually. This bug not related to fastify-oas. . Fastify-oas generates open api schema from JSON schema that is used in fastify. So you should either define format keyword for numbers and pass your customized ajv instance to fastify or just omit that format.
